-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-24 21:40:33 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE auto (
    cust_id        INTEGER NOT NULL,
    license_plate  VARCHAR2(15 CHAR) NOT NULL,
    manufacturer   VARCHAR2(35 CHAR),
    model          VARCHAR2(35 CHAR),
    year           INTEGER
);

ALTER TABLE auto ADD CONSTRAINT auto_pk PRIMARY KEY ( license_plate );

CREATE TABLE collision_type (
    collision_type VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE collision_type ADD CONSTRAINT collision_type_pk PRIMARY KEY ( collision_type );

CREATE TABLE customer (
    cust_id         INTEGER NOT NULL,
    cust_name       VARCHAR2(50 CHAR),
    age             INTEGER,
    sex             VARCHAR2(10 CHAR),
    education_type  VARCHAR2(50 CHAR)
);

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE education_type (
    education_type VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE education_type ADD CONSTRAINT education_type_pk PRIMARY KEY ( education_type );

CREATE TABLE incident (
    incident_id     INTEGER NOT NULL,
    incident_date   DATE,
    collision_type  VARCHAR2(50 CHAR),
    incident_type   VARCHAR2(50 CHAR)
);

ALTER TABLE incident ADD CONSTRAINT incident_pk PRIMARY KEY ( incident_id );

CREATE TABLE incident_type (
    incident_type VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE incident_type ADD CONSTRAINT incident_type_pk PRIMARY KEY ( incident_type );

CREATE TABLE insurance_claim (
    incident_id    INTEGER NOT NULL,
    capital_gains  INTEGER,
    capital_loss   INTEGER,
    policy_number  INTEGER NOT NULL
);

CREATE TABLE policy (
    policy_number   INTEGER NOT NULL,
    license_plate   VARCHAR2(15 CHAR) NOT NULL,
    annual_premium  NUMBER(6, 2),
    umbrella_limit  INTEGER
);

ALTER TABLE policy ADD CONSTRAINT policy_pk PRIMARY KEY ( policy_number );

ALTER TABLE policy
    ADD CONSTRAINT auto_fk FOREIGN KEY ( license_plate )
        REFERENCES auto ( license_plate );

ALTER TABLE incident
    ADD CONSTRAINT collision_type_fk FOREIGN KEY ( collision_type )
        REFERENCES collision_type ( collision_type );

ALTER TABLE auto
    ADD CONSTRAINT customer_fk FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE customer
    ADD CONSTRAINT education_type_fk FOREIGN KEY ( education_type )
        REFERENCES education_type ( education_type );

ALTER TABLE insurance_claim
    ADD CONSTRAINT incident_fk FOREIGN KEY ( incident_id )
        REFERENCES incident ( incident_id )
            ON DELETE CASCADE;

ALTER TABLE incident
    ADD CONSTRAINT incident_type_fk FOREIGN KEY ( incident_type )
        REFERENCES incident_type ( incident_type );

ALTER TABLE insurance_claim
    ADD CONSTRAINT policy_fk FOREIGN KEY ( policy_number )
        REFERENCES policy ( policy_number )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             14
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
